#!/bin/bash
echo "-"$(date "+%a, %e. %b, %H:%M")
if [[ $BLOCK_BUTTON == '1' ]]; then
         urxvt -title "float" -geometry 120x40 -hold -e \
                 ikhal 
fi
if [[ $BLOCK_BUTTON == '3' ]]; then
        notify-send "`python ~/.config/i3/statusbar/calendar-events.py`"
fi

