#!/bin/bash

DIR="${BLOCK_INSTANCE:-$HOME}"
ALERT_LOW="${100:-20}" # color will turn red above this value (default: 80%)

usage=$(df -h -P -l "$DIR" | awk -v alert_low=$ALERT_LOW '
/\/.*/ {
    print $5
        use=$5
            # no need to continue parsing
                exit 0
            }

            END {
                gsub(/%$/,"",use)
                    if (100 - use < alert_low) {
                                # color
                                print "#CC6666"
                                    }}')        

        echo "-Sys Space used:" $usage"G"
        if [[ $BLOCK_BUTTON == '1' ]]; then
                urxvt -title "float" -geometry 80x35 -hold -e df -a
        fi
