#!/bin/bash

res=$(rofi -p "> " -dmenu < ~/.config/i3/powermenu)

if [ $res = "lock" ]; then
	exec env XSECURELOCK_SAVER=saver_mpv XSECURELOCK_DISCARD_FIRST_KEYPRESS=0 XSECURELOCK_IMAGE_DURATION_SECONDS=8 XSECURELOCK_LIST_VIDEOS_COMMAND='find ~/Images/screensaver/blade_runner -type f' xsecurelock
fi
if [ $res = "logout" ]; then
	i3-msg exit
fi
if [ $res = "restart" ]; then
	reboot
fi
if [ $res = "shutdown" ]; then
	poweroff
fi
exit 0
